### ISSUE TITLE
Meeples abilities not working

### ISSUE THREAD

**Issue by ckiyme** [andothergames/MM#1]
I was trying the game and I believe none of the meeples ability works.
I tried both by clicking the star or holding it. After having selected the meeple and before selecting the meeple. I also tried using both Firefox and Chrome.

Not sure if it is because you haven't implemented the functionality yet on `main` or it is an actual bug.

**Comment by andothergames** [comment]
Hey, yeah the abilities are still massively in progress as implementing them is proving tricky. Thanks for checking out the game and your feedback!

Sent from phone

On 7 Apr 2024, at 11:32, Michele Maria Serrapica ***@***.***> wrote:

﻿

I was trying the game and I believe none of the meeples ability works.
I tried both by clicking the star or holding it. After having selected the meeple and before selecting the meeple. I also tried using both Firefox and Chrome.

Not sure if it is because you haven't implemented the functionality yet on main or it is an actual bug.

**Comment by ckiyme** [comment]
No worries.
I was playing with it because I like this kind of puzzle games!

Also, as a former _bootcamper_, I just want to say I have massive respect for what you're doing here. 
I was never able to do something more than the homework while attending it. So, seeing you building a whole game is just impressive.

Happy to try to help with the issues if you ever feel like you might need an extra brain. 🧠

**Comment by yanader** [comment]
Issue raised incorrectly as per README
